const STORAGE_KEY='pourLabRecipes';
const ACTIVE_KEY='pourLabActiveRecipeId';
const MAX_RECIPES=40;
const DEFAULT_RECIPE=Object.freeze({name:'V60 · 15:250',dose:15,water:250,temperature:92,targetFlow:5,bloomWater:40,bloomSeconds:40,stages:[{id:'bloom',name:'闷蒸',fromWater:0,toWater:40,targetFlow:3.5,pauseAfter:30},{id:'main',name:'主体注水',fromWater:40,toWater:180,targetFlow:5,pauseAfter:0},{id:'finish',name:'收尾',fromWater:180,toWater:250,targetFlow:4.5,pauseAfter:0}]});
const finite=(v,f)=>Number.isFinite(Number(v))?Number(v):f;
const safeParse=(text,fallback)=>{try{return JSON.parse(text)}catch{return fallback}};
function recipeId(recipe){return recipe?.id||`recipe-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
export function normalizeRecipe(input={}){const water=Math.max(50,finite(input.water,DEFAULT_RECIPE.water)),dose=Math.max(1,finite(input.dose,DEFAULT_RECIPE.dose)),temperature=Math.min(100,Math.max(60,finite(input.temperature,DEFAULT_RECIPE.temperature))),targetFlow=Math.min(10,Math.max(1,finite(input.targetFlow,DEFAULT_RECIPE.targetFlow))),bloomWater=Math.min(water*.45,Math.max(0,finite(input.bloomWater,DEFAULT_RECIPE.bloomWater))),bloomSeconds=Math.min(180,Math.max(0,finite(input.bloomSeconds,DEFAULT_RECIPE.bloomSeconds)));let stages=Array.isArray(input.stages)?input.stages:DEFAULT_RECIPE.stages;stages=stages.map((stage,index)=>({id:String(stage?.id||`stage-${index+1}`),name:String(stage?.name||`阶段 ${index+1}`),fromWater:Math.max(0,finite(stage?.fromWater,0)),toWater:Math.min(water,Math.max(0,finite(stage?.toWater,water))),targetFlow:Math.min(10,Math.max(1,finite(stage?.targetFlow,targetFlow))),pauseAfter:Math.min(180,Math.max(0,finite(stage?.pauseAfter,0)))})).filter(stage=>stage.toWater>stage.fromWater).sort((a,b)=>a.fromWater-b.fromWater);if(!stages.length)stages=[{id:'main',name:'主体注水',fromWater:0,toWater:water,targetFlow,pauseAfter:0}];return {version:1,id:recipeId(input),name:String(input.name||`${dose}g · ${water}g`),dose,water,ratio:Number((water/dose).toFixed(2)),temperature,targetFlow,bloomWater,bloomSeconds,stages,createdAt:input.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),parentId:input.parentId||null};}
export function defaultRecipe(){return normalizeRecipe({...DEFAULT_RECIPE,id:'recipe-default-v60',createdAt:'2026-08-24T00:00:00.000Z'});}
export function readRecipes(storage=globalThis.localStorage){try{const value=safeParse(storage?.getItem?.(STORAGE_KEY)||'[]',[]);const normalized=(Array.isArray(value)?value:[]).map(normalizeRecipe);return normalized.length?normalized:[defaultRecipe()]}catch{return [defaultRecipe()]}}
export function persistRecipes(storage=globalThis.localStorage,recipes=[]){const normalized=(Array.isArray(recipes)?recipes:[]).map(normalizeRecipe).slice(0,MAX_RECIPES);try{storage?.setItem?.(STORAGE_KEY,JSON.stringify(normalized));return {ok:true,recipes:normalized}}catch{return {ok:false,recipes:normalized}}}
export function saveRecipe(storage,recipe){const next=normalizeRecipe(recipe);const recipes=readRecipes(storage).filter(item=>item.id!==next.id);return persistRecipes(storage,[next,...recipes]);}
export function forkRecipe(recipe,overrides={}){const parent=normalizeRecipe(recipe);return normalizeRecipe({...parent,...overrides,id:undefined,parentId:parent.id,name:overrides.name||`${parent.name} · Fork`,createdAt:undefined});}
export function setActiveRecipe(storage,id){const exists=readRecipes(storage).some(recipe=>recipe.id===id);if(!exists)return false;try{storage?.setItem?.(ACTIVE_KEY,id);return true}catch{return false}}
export function activeRecipe(storage=globalThis.localStorage){const recipes=readRecipes(storage);let id=null;try{id=storage?.getItem?.(ACTIVE_KEY)||null}catch{}return recipes.find(recipe=>recipe.id===id)||recipes[0]||defaultRecipe()}
export function recipeStageAtWater(recipe,water){const normalized=normalizeRecipe(recipe),w=Math.max(0,finite(water,0));return normalized.stages.find(stage=>w>=stage.fromWater&&w<stage.toWater)||normalized.stages.at(-1);}
export function serializeRecipe(recipe,{pretty=true}={}){return JSON.stringify(normalizeRecipe(recipe),null,pretty?2:0)}
export function parseRecipe(text){let parsed;try{parsed=typeof text==='string'?JSON.parse(text):text}catch{return {ok:false,reason:'invalid-json',recipe:null}};if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))return {ok:false,reason:'unsupported-format',recipe:null};const recipe=normalizeRecipe(parsed);return {ok:true,reason:null,recipe};}
export const RECIPE_STORAGE_KEY=STORAGE_KEY;
export const ACTIVE_RECIPE_STORAGE_KEY=ACTIVE_KEY;
