import assert from 'node:assert/strict';
import {normalizeHistory,addBrewToHistory,bestBrew,readBrewHistory,persistLatestBrew,selectGhostReference,downsampleSamples,compactReplay,persistHistory} from '../pour-brew-history.js';
const samples=n=>Array.from({length:n},(_,i)=>({t:i*100,x:i/1000,z:-i/2000,flow:5,water:i*.4,pouring:i%7!==0}));
const brew=(n,score=n,count=1)=>({createdAt:`2026-08-${String(n).padStart(2,'0')}T00:00:00.000Z`,duration:n*1000,score,samples:samples(count)});
const ds=downsampleSamples(samples(5000),900);assert.equal(ds.length,900);assert.equal(ds[0].t,0);assert.equal(ds.at(-1).t,499900);
const compact=compactReplay(brew(1,90,5000));assert.equal(compact.samples.length,900);assert.equal(compact.sourceSampleCount,5000);
let h=[];for(let i=1;i<=35;i++)h=addBrewToHistory(h,brew(i,i,1200));assert.equal(h.length,30);assert.equal(h[0].score,35);assert.equal(h.at(-1).score,6);assert(h.every(x=>x.samples.length<=900));
const duplicate=addBrewToHistory(h,brew(35,35,1200));assert.equal(duplicate.length,30);assert.equal(new Set(duplicate.map(x=>x.id)).size,30);
assert.equal(bestBrew([brew(1,70),brew(2,94),brew(3,82)]).score,94);assert.equal(normalizeHistory([null,{}, {samples:[]}]).length,0);
const store=new Map();const storage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,v)};storage.setItem('pourLabLastBrew',JSON.stringify(brew(9,88,5000)));let saved=persistLatestBrew(storage);assert.equal(saved.length,1);assert.equal(saved[0].samples.length,900);saved=persistLatestBrew(storage);assert.equal(saved.length,1);assert.equal(readBrewHistory(storage)[0].score,88);
let writes=0;const quotaStorage={getItem:()=>null,setItem:(k,v)=>{writes++;const parsed=JSON.parse(v);const sampleCount=parsed.reduce((s,b)=>s+b.samples.length,0);if(sampleCount>5000)throw Object.assign(new Error('quota'),{name:'QuotaExceededError'})}};const many=Array.from({length:30},(_,i)=>brew(i+1,80+i,1600));const degraded=persistHistory(quotaStorage,many);assert.equal(degraded.ok,true);assert.equal(degraded.degraded,true);assert(writes>1);assert(degraded.history.reduce((s,b)=>s+b.samples.length,0)<=5000);
const brokenStorage={getItem(){throw new Error('private mode')},setItem(){throw new Error('private mode')}};assert.deepEqual(readBrewHistory(brokenStorage),[]);assert.deepEqual(persistLatestBrew(brokenStorage),[]);assert.equal(selectGhostReference(brokenStorage,brew(4,91)),false);
const ref=brew(4,91);assert.equal(selectGhostReference(storage,ref),true);assert.equal(JSON.parse(storage.getItem('pourLabLastBrew')).score,91);assert.equal(selectGhostReference(storage,null),false);
console.log('brew history tests: PASS');
