import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');

assert.match(html, /createFlowRuntime/);
assert.match(html, /createBedPhysics/);
assert.match(html, /sampleBallisticArc/);
assert.match(html, /createStreamMotionRuntime/);
assert.match(html, /shouldRefreshStream/);
assert.match(html, /createReusableStreamGeometry/);
assert.match(html, /createLifecycleClock/);
assert.match(html, /createPageLifecycleController/);
assert.match(html, /const flowRuntime=createFlowRuntime\([^\n]+trainClock=createLifecycleClock\(\),replayClock=createLifecycleClock\(\)/);
assert.match(html, /trainClock\.start\(now\)/);
assert.match(html, /replayClock\.start\(now\)/);
assert.match(html, /trainClock\.elapsed\(now\)/);
assert.match(html, /replayClock\.elapsed\(now\)/);
assert.match(html, /pageLifecycle\.suspend\(reason,performance\.now\(\)\)/);
assert.match(html, /pageLifecycle\.resume\(reason,performance\.now\(\)\)/);
assert.match(html, /document\.addEventListener\('visibilitychange'/);
assert.match(html, /addEventListener\('blur'/);
assert.match(html, /addEventListener\('focus'/);
assert.match(html, /onSuspend:\(\{at\}\)=>\{replayClock\.pause\(at\);pouring=false;lastPouring=false;lastT=at;stream\.visible=false\}/);
assert.match(html, /onResume:\(\{at\}\)=>\{replayClock\.resume\(at\);lastT=at\}/);
assert.match(html, /runtime=flowRuntime\.step\(dt,pouring\)/);
assert.match(html, /motionRuntime\.setDesired\(desiredPoint\)/);
assert.match(html, /targetPoint\.set\(motion\.actual\.x,motion\.actual\.y,motion\.actual\.z\)/);
assert.match(html, /kettle\.position\.set\(motion\.kettle\.x,motion\.kettle\.y,motion\.kettle\.z\)/);
assert.match(html, /bedPhysics\.deposit\(targetPoint\.x,targetPoint\.z,runtime\.addedWater\)/);
assert.match(html, /flow:runtime\.actualFlow,water:runtime\.water/);
assert.match(html, /kettle\.rotation\.z=runtime\.tilt/);
assert.match(html, /runtime\.streamRadius/);
assert.match(html, /sampleBallisticArc\(start,end,runtime\.actualFlow,\{segments:16\}\)/);
assert.match(html, /const streamGeometry=createReusableStreamGeometry\(THREE,\{segments:16,radialSegments:6\}\)/);
assert.match(html, /streamGeometry\.update\(ballisticPoints\(start,targetPoint\),runtime\.streamRadius\)/);
assert.match(html, /new THREE\.Mesh\(streamGeometry\.geometry,streamMaterial\)/);
assert.match(html, /stream\.visible=false/);
assert.doesNotMatch(html, /performance\.now\(\)-startAt/);
assert.doesNotMatch(html, /now-startAt/);
assert.doesNotMatch(html, /now-replayStart/);
assert.doesNotMatch(html, /targetPoint\.set\(hit\.x,1\.18,hit\.z\);marker/);
assert.doesNotMatch(html, /kettle\.position\.set\(hit\.x\+1\.72,3\.15,hit\.z\+\.08\)/);
assert.doesNotMatch(html, /stream\.material\.dispose\(\)/);
assert.doesNotMatch(html, /stream\.geometry\.dispose\(\)/);
assert.doesNotMatch(html, /nextGeometry/);
assert.doesNotMatch(html, /new THREE\.TubeGeometry\(new THREE\.CatmullRomCurve3\(ballisticPoints/);
assert.doesNotMatch(html, /water\s*\+=\s*flow\s*\*\s*dt/);
assert.doesNotMatch(html, /kettle\.rotation\.z=-Math\.min\([^\n]*runtime\.tilt/);
assert.doesNotMatch(html, /\.010\s*\+\s*runtime\.actualFlow\s*\*\s*\.0022/);
assert.doesNotMatch(html, /vy=-\.18/);
assert.doesNotMatch(html, /const G=5\.5/);

console.log('index physics integration tests: PASS');
