import { readFileSync, writeFileSync, mkdirSync, rmSync, cpSync } from 'node:fs';
import { join } from 'node:path';

const languageBootstrap = readFileSync('public/language.js', 'utf8');
const data = JSON.parse(readFileSync('gallery-index.json', 'utf8'));
const selection = JSON.parse(readFileSync('curation.json', 'utf8'));
const names = { Australia: ['澳大利亚', 'Australia'], Bankok: ['曼谷', 'Bangkok'], Chaozhou: ['潮州', 'Chaozhou'], Hongkong: ['香港', 'Hong Kong'], Jeju: ['济州岛', 'Jeju'], Kyoto: ['京都', 'Kyoto'], Macau: ['澳门', 'Macau'], Nanjing: ['南京', 'Nanjing'], Osaka: ['大阪', 'Osaka'], Other: ['途中', 'Elsewhere'], Shanghai: ['上海', 'Shanghai'], Singapore: ['新加坡', 'Singapore'], Tokyo: ['东京', 'Tokyo'], Vietnam: ['越南', 'Vietnam'], Xiamen: ['厦门', 'Xiamen'], exhibition: ['展览现场', 'Exhibitions'] };
const all = Object.values(data.gallery).flatMap(category => category.images);
const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
const find = pick => {
  const image = all.find(item => item.category === pick.category && item.name === pick.name);
  if (!image) throw new Error(`Missing selection: ${pick.category}/${pick.name}`);
  const caption = [...selection.hero, ...selection.selected].find(item => item.category === pick.category && item.name === pick.name);
  return { ...image, ...caption, ...pick };
};
const selected = selection.selected.map(find), hero = selection.hero.map(find);
let language = 'zh';
const t = (zh, en) => language === 'en' ? en : zh;
const local = path => language === 'en' ? '/en' + path : path;
const english = category => names[category]?.[1] || category;
const place = category => t(names[category]?.[0] || category, english(category));
const categoryPath = category => local(`/works/${encodeURIComponent(category)}/`);
const photo = (image, index = 0, large = false, priority = false) => {
  const label = t(image.title, image.titleEn) || `${place(image.category)} · ${image.name}`;
  const full = large && image.largePreview ? image.largePreview : image.preview;
  return `<figure class="photo${large ? ' photo-large' : ''}"><a class="photo-open" href="${esc(image.original)}" target="_blank" rel="noopener noreferrer" data-photo data-photo-id="${esc(image.category + '/' + image.name)}" data-preview="${esc(full)}" data-title="${esc(label)}" data-place="${esc(place(image.category))}" aria-label="${t('查看作品：', 'View photograph: ')}${esc(label)}"><img src="${esc(image.preview)}" ${full !== image.preview ? `srcset="${esc(image.preview)} 960w, ${esc(full)} 1600w" sizes="(max-width: 700px) 100vw, 75vw"` : ''} width="${image.width || 1500}" height="${image.height || 1000}" alt="${esc(t(image.description, image.descriptionEn) || label)}" loading="${priority ? 'eager' : 'lazy'}" ${priority ? 'fetchpriority="high"' : ''} decoding="async"></a><figcaption><span>${esc(label)}</span><span class="photo-index">${String(index + 1).padStart(2, '0')} / ${esc(english(image.category))}</span></figcaption></figure>`;
};
const nav = (active, path) => `<a class="skip" href="#main">${t('跳到作品', 'Skip to content')}</a><header class="site-header"><a class="wordmark" href="${local('/')}" aria-label="${t('Power’s Gallery 首页', 'Power’s Gallery home')}">Power’s Gallery<span>PHOTOGRAPHY</span></a><div class="header-controls"><a class="language-switch" href="${language === 'en' ? path : '/en' + path}" data-language="${t('en', 'zh')}" lang="${t('en', 'zh-CN')}" aria-label="${t('Switch to English', '切换为中文')}">${t('EN', '中')}</a><button class="menu-toggle" type="button" aria-label="${t('打开导航', 'Open navigation')}" aria-expanded="false" aria-controls="site-nav"><span></span><span></span></button></div><nav id="site-nav" aria-label="${t('主导航', 'Main navigation')}">${[['works', '/works/', '作品', 'Works'], ['places', '/places/', '地点', 'Places'], ['about', '/about/', '关于', 'About']].map(([key, href, zh, en]) => `<a href="${local(href)}" ${active === key ? 'aria-current="page"' : ''}>${t(zh, en)}<span>${t(en.toUpperCase(), { works: 'PHOTOGRAPHS', places: 'JOURNEYS', about: 'CONTACT' }[key])}</span></a>`).join('')}</nav></header>`;
const footer = () => `<footer class="site-footer"><a class="footer-name" href="${local('/')}">Power’s Gallery</a><p>${t('风光与人文摄影', 'Landscape & people')}<span>LANDSCAPE & HUMAN STORIES</span></p><a href="https://gallery.wiki-power.com/" target="_blank" rel="noopener noreferrer">${t('原版相册', 'Original gallery')} ↗</a><span class="copyright">© ${new Date().getFullYear()} Power’s Gallery</span></footer>`;
const viewer = () => `<dialog id="viewer" aria-label="${t('作品大图', 'Photograph viewer')}" aria-labelledby="viewer-title"><div class="viewer-top"><span id="viewer-place"></span><button id="viewer-close" type="button" aria-label="${t('关闭大图', 'Close photograph')}">✕</button></div><div class="viewer-stage"><img id="viewer-image" alt=""><span id="viewer-watermark" aria-hidden="true">© Power’s Gallery</span></div><div class="viewer-footer"><div><span id="viewer-title"></span><p id="viewer-status" role="status" aria-live="polite"></p></div><div class="viewer-actions"><button id="viewer-previous" type="button" aria-label="${t('上一张作品', 'Previous photograph')}">←</button><button id="viewer-next" type="button" aria-label="${t('下一张作品', 'Next photograph')}">→</button><button id="viewer-share" type="button">${t('复制链接', 'Copy link')}</button><button id="viewer-original" type="button">${t('加载原图', 'Load original')}</button><button id="viewer-zoom" type="button" hidden>${t('100% 查看', 'View at 100%')}</button><a id="viewer-link" target="_blank" rel="noopener noreferrer">${t('打开原图', 'Open original')} ↗</a></div></div></dialog>`;
const page = (title, description, body, active = '', path = '/') => `<!doctype html><html lang="${t('zh-CN', 'en')}" data-language="${language}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#f7f6f2"><script>${languageBootstrap}</script><title>${esc(title)} · Power’s Gallery</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="https://gallery-beta.wiki-power.com${local(path)}"><link rel="alternate" hreflang="zh-CN" href="https://gallery-beta.wiki-power.com${path}"><link rel="alternate" hreflang="en" href="https://gallery-beta.wiki-power.com/en${path}"><meta property="og:title" content="${esc(title)} · Power’s Gallery"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:image" content="https://gallery-beta.wiki-power.com${hero[0].largePreview || hero[0].preview}"><link rel="icon" href="/public/assets/favicon.svg" type="image/svg+xml"><link rel="preconnect" href="https://media.wiki-power.com"><link rel="stylesheet" href="/public/beta.css?v=3"><script src="/public/beta.js?v=3" defer></script></head><body>${nav(active, path)}<main id="main">${body}</main>${footer()}${viewer()}</body></html>`;
const heading = (kicker, title, text) => `<div class="page-heading"><span class="eyebrow">${kicker}</span><h1>${title}</h1><p>${text}</p></div>`;
const filters = current => `<nav class="filters" aria-label="${t('作品地点', 'Photograph locations')}"><a href="${local('/works/')}" ${!current ? 'aria-current="page"' : ''}>${t('全部', 'All')}<span>${all.length}</span></a>${Object.keys(data.gallery).map(category => `<a href="${categoryPath(category)}" ${current === category ? 'aria-current="page"' : ''}>${esc(place(category))}<span>${data.gallery[category].images.length}</span></a>`).join('')}</nav>`;
const cover = category => find(selection.covers[category] || { category, name: data.gallery[category].images[0].name });
const placeCard = category => `<a class="place-card" href="${categoryPath(category)}"><div class="place-image"><img src="${esc(cover(category).preview)}" alt="${esc(place(category))} ${t('摄影作品', 'photographs')}" width="${cover(category).width}" height="${cover(category).height}" loading="lazy" decoding="async"></div><div class="place-caption"><h3>${esc(place(category))}<span>${t(esc(english(category)), 'PHOTOGRAPHIC JOURNEY')}</span></h3><span>${data.gallery[category].images.length} ${t('件作品', 'works')} ↗</span></div></a>`;

rmSync('dist', { recursive: true, force: true }); mkdirSync('dist', { recursive: true });
cpSync('public', 'dist/public', { recursive: true }); cpSync('_headers', 'dist/_headers');
const routes = [], redirects = [];
const write = (path, html) => {
  const relative = local('/' + path).slice(1), dir = join('dist', relative);
  mkdirSync(dir, { recursive: true }); writeFileSync(join(dir, 'index.html'), html);
  routes.push(local('/' + (path ? path + '/' : '')));
};
const ordered = [...selected, ...all.filter(image => !selected.some(item => item.original === image.original))];
for (language of ['zh', 'en']) {
  const homepage = `<section class="intro"><div><span class="eyebrow">SELECTED PHOTOGRAPHY</span><h1>${t('风光<span class="ampersand">与</span>人文', 'Landscape<span class="ampersand">&</span>people')}<span class="intro-english">PHOTOGRAPHY</span></h1></div><p>${t('在山川与日常之间，<br>看见人与地方的关系。', 'Between landscapes and daily life,<br>seeing people in their surroundings.')}<span>LANDSCAPE & HUMAN STORIES</span></p></section><section class="hero-pair" aria-label="${t('封面作品', 'Featured photographs')}">${hero.map((image, i) => photo(image, i, true, i === 0)).join('')}</section><section class="selected-section"><div class="section-heading"><div><span class="eyebrow">01 / SELECTED WORKS</span><h2>${t('精选作品', 'Selected works')}</h2></div><a class="text-link" href="${local('/works/')}">${t(`浏览全部 ${all.length} 件作品`, `View all ${all.length} photographs`)} <span>↗</span></a></div><div class="selected-grid">${selected.map((image, i) => photo(image, i)).join('')}</div></section><section class="places-section"><div class="section-heading"><div><span class="eyebrow">02 / PLACES & JOURNEYS</span><h2>${t('沿途所见', 'Places & journeys')}</h2></div><a class="text-link" href="${local('/places/')}">${t('探索全部地点', 'Explore all places')} <span>↗</span></a></div><div class="place-grid">${selection.featuredPlaces.map(placeCard).join('')}</div></section><section class="artist-note"><span class="eyebrow">03 / BEHIND THE LENS</span><h2>${t('风景有尺度，<br>日常有温度。', 'Scale in landscapes.<br>Warmth in daily life.')}</h2><div><p>${t('用摄影记录远方的风景，<br>也记录街巷中平常的一刻。', 'Photographs of distant landscapes,<br>and ordinary moments along the way.')}</p><a class="text-link" href="${local('/about/')}">${t('关于摄影师', 'About the photographer')} <span>↗</span></a></div></section>`;
  write('', page(t('风光与人文摄影', 'Landscape & people'), t('Power’s Gallery 的个人摄影作品，记录风景、城市与日常。', 'A personal collection of landscape, city and everyday photography by Power.'), homepage));
  write('works', page(t('全部作品', 'All photographs'), t('浏览 Power’s Gallery 的全部风光与人文摄影作品，可按地点选择并查看原图。', 'Explore the full archive by location and view the original photographs.'), `${heading('THE PHOTOGRAPHIC ARCHIVE', t('作品档案', 'The archive'), t(`${all.length} 件作品 · ${Object.keys(data.gallery).length} 个相册`, `${all.length} photographs · ${Object.keys(data.gallery).length} collections`))}${filters()}<div class="archive-grid">${ordered.map((image, i) => photo(image, i)).join('')}</div>`, 'works', '/works/'));
  for (const [category, value] of Object.entries(data.gallery)) {
    const images = [...selected.filter(image => image.category === category), ...value.images.filter(image => !selected.some(item => item.original === image.original))];
    write(`works/${category}`, page(place(category), t(`${place(category)}的摄影记录，共 ${images.length} 件作品。`, `${images.length} photographs from ${place(category)}.`), `${heading(esc(english(category).toUpperCase()), esc(place(category)), t(`${images.length} 件作品 · 点击照片查看大图与原图`, `${images.length} photographs · Select a photograph to view its original`))}${filters(category)}<div class="archive-grid">${images.map((image, i) => photo(image, i)).join('')}</div>`, 'works', `/works/${category}/`));
    redirects.push(`${local('/' + category)} ${categoryPath(category)} 301`);
  }
  write('places', page(t('地点', 'Places'), t('沿地点浏览 Power’s Gallery 的摄影旅程。', 'Explore the photographic journeys in Power’s Gallery.'), `${heading('PLACES & JOURNEYS', t('沿途所见', 'Places & journeys'), t('从一个地方，走进一组照片。', 'A place, a collection, a different way of seeing.'))}<div class="place-grid all-places">${Object.keys(data.gallery).map(placeCard).join('')}</div>`, 'places', '/places/'));
  const about = `<section class="about-layout"><div>${heading('BEHIND THE LENS', 'Power’s Gallery', t('风光与人文摄影 / PHOTOGRAPHY', 'LANDSCAPE & HUMAN STORIES'))}<h2>${t('在山川与日常之间。', 'Between landscapes and daily life.')}</h2><p>${t('记录风景、城市，以及人与地方的关系。<br>既看辽阔的远方，也看街巷里平常的一刻。', 'Photographs of landscapes, cities and the relationship between people and places.<br>A view of the wider world, and the ordinary moments within it.')}</p><p>${t('这里是我的个人摄影作品档案。<br>你可以从精选作品开始，也可以按地点慢慢浏览。', 'This is my personal photographic archive.<br>Begin with the selected works, or take your time exploring by place.')}</p><section class="contact-note" aria-labelledby="contact-heading"><span class="eyebrow">COLLABORATIONS & COLLECTIONS</span><h2 id="contact-heading">${t('合作与作品收藏', 'Collaborations & collecting')}</h2><p>${t('摄影合作、作品授权与购买，欢迎来信。<br>请附上感兴趣的作品链接，以及用途或合作想法。', 'For photography collaborations, licensing or purchasing works, please get in touch.<br>Include a link to the photograph and a few words about your project or intended use.')}</p><a class="contact-email" href="mailto:linyuxuanlin@outlook.com?subject=${encodeURIComponent(t('摄影合作与作品咨询', 'Photography collaboration and artwork inquiry'))}">linyuxuanlin@outlook.com <span>↗</span></a></section><section class="copyright-note" aria-labelledby="copyright-heading"><h2 id="copyright-heading">${t('版权声明', 'Copyright')}</h2><p>${t('本站摄影作品版权归 Power 所有。未经许可，请勿复制、转载或用于商业用途。浏览与下载原图不代表取得作品使用授权；如需授权或购买，请通过以上邮箱联系。', 'All photographs on this website are copyright © Power. Please do not reproduce, republish or use them commercially without permission. Viewing or downloading an original does not grant a licence to use it. For licensing or purchases, contact the email above.')}</p></section><div class="about-links"><a class="text-link" href="${local('/works/')}">${t('浏览作品', 'Explore the works')} ↗</a><a class="text-link" href="https://wiki-power.com/" target="_blank" rel="noopener noreferrer">${t('个人网站', 'Personal website')} ↗</a><a class="text-link" href="https://github.com/linyuxuanlin" target="_blank" rel="noopener noreferrer">GitHub ↗</a></div></div>${photo(find(selection.about), 0, true)}</section>`;
  write('about', page(t('关于', 'About'), t('Power’s Gallery，风光与人文摄影。', 'About Power’s Gallery. Collaborations, licensing and artwork inquiries.'), about, 'about', '/about/'));
  const missing = page(t('这一页尚未抵达', 'Off the map'), t('找不到这个页面。', 'This page could not be found.'), `${heading('404 / OFF THE MAP', t('这一页尚未抵达。', 'This page is off the map.'), t('回到作品，继续看见。', 'Return to the archive and keep exploring.'))}<a class="text-link" href="${local('/works/')}">${t('返回作品档案', 'Return to the archive')} ↗</a>`);
  writeFileSync(join('dist', language === 'en' ? 'en/404.html' : '404.html'), missing);
}
writeFileSync('dist/_redirects', redirects.join('\n') + '\n');
writeFileSync('dist/robots.txt', 'User-agent: *\nAllow: /\nSitemap: https://gallery-beta.wiki-power.com/sitemap.xml\n');
writeFileSync('dist/sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${routes.map(path => `<url><loc>https://gallery-beta.wiki-power.com${path}</loc></url>`).join('')}</urlset>`);
// Prebuilt root supports the existing Pages project's static branch previews.
for (const route of routes) {
  const relative = route.slice(1); mkdirSync(relative || '.', { recursive: true });
  cpSync(join('dist', relative, 'index.html'), join(relative, 'index.html'));
}
for (const file of ['404.html', 'en/404.html', '_redirects', 'robots.txt', 'sitemap.xml']) cpSync(join('dist', file), file);
console.log(`Built ${routes.length} bilingual pages, ${all.length} photos, ${selected.length} selected works.`);
