import { readFileSync, writeFileSync, mkdirSync, rmSync, cpSync } from 'node:fs';
import { join } from 'node:path';

const data = JSON.parse(readFileSync('gallery-index.json', 'utf8'));
const selection = JSON.parse(readFileSync('curation.json', 'utf8'));
const names = { Australia: ['澳大利亚', 'Australia'], Bankok: ['曼谷', 'Bangkok'], Chaozhou: ['潮州', 'Chaozhou'], Hongkong: ['香港', 'Hong Kong'], Jeju: ['济州岛', 'Jeju'], Kyoto: ['京都', 'Kyoto'], Macau: ['澳门', 'Macau'], Nanjing: ['南京', 'Nanjing'], Osaka: ['大阪', 'Osaka'], Other: ['途中', 'Elsewhere'], Shanghai: ['上海', 'Shanghai'], Singapore: ['新加坡', 'Singapore'], Tokyo: ['东京', 'Tokyo'], Vietnam: ['越南', 'Vietnam'], Xiamen: ['厦门', 'Xiamen'], exhibition: ['展览现场', 'Exhibitions'] };
const all = Object.values(data.gallery).flatMap(category => category.images);
const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
const find = pick => { const image = all.find(item => item.category === pick.category && item.name === pick.name); if (!image) throw new Error(`Missing selection: ${pick.category}/${pick.name}`); return { ...image, ...pick }; };
const selected = selection.selected.map(find);
const hero = selection.hero.map(find);
const place = category => names[category]?.[0] || category;
const english = category => names[category]?.[1] || category;
const categoryPath = category => `/works/${encodeURIComponent(category)}/`;
const photo = (image, index = 0, large = false, priority = false) => {
  const label = image.title || `${place(image.category)} · ${image.name}`;
  const full = large && image.largePreview ? image.largePreview : image.preview;
  return `<figure class="photo${large ? ' photo-large' : ''}"><a class="photo-open" href="${esc(image.original)}" target="_blank" rel="noopener noreferrer" data-photo data-preview="${esc(full)}" data-title="${esc(label)}" data-place="${esc(place(image.category))}" aria-label="查看作品：${esc(label)}"><img src="${esc(image.preview)}" ${full !== image.preview ? `srcset="${esc(image.preview)} 960w, ${esc(full)} 1600w" sizes="(max-width: 700px) 100vw, 75vw"` : ''} width="${image.width || 1500}" height="${image.height || 1000}" alt="${esc(image.description || label)}" loading="${priority ? 'eager' : 'lazy'}" ${priority ? 'fetchpriority="high"' : ''} decoding="async"></a><figcaption><span>${esc(label)}</span><span class="photo-index">${String(index + 1).padStart(2, '0')} / ${esc(english(image.category))}</span></figcaption></figure>`;
};
const nav = active => `<a class="skip" href="#main">跳到作品</a><header class="site-header"><a class="wordmark" href="/" aria-label="POWER LIN 首页">POWER LIN<span>PHOTOGRAPHY</span></a><button class="menu-toggle" type="button" aria-label="打开导航" aria-expanded="false" aria-controls="site-nav"><span></span><span></span></button><nav id="site-nav" aria-label="主导航">${[['works', '/works/', '作品'], ['places', '/places/', '地点'], ['about', '/about/', '关于']].map(([key, href, text]) => `<a href="${href}" ${active === key ? 'aria-current="page"' : ''}>${text}<span>${key.toUpperCase()}</span></a>`).join('')}</nav></header>`;
const footer = `<footer class="site-footer"><a class="footer-name" href="/">POWER LIN</a><p>风光与人文摄影<span>LANDSCAPE & HUMAN STORIES</span></p><a href="https://gallery.wiki-power.com/" target="_blank" rel="noopener noreferrer">原版相册 ↗</a><span class="copyright">© ${new Date().getFullYear()} POWER LIN</span></footer>`;
const viewer = `<dialog id="viewer" aria-label="作品大图"><div class="viewer-top"><span id="viewer-place"></span><button id="viewer-close" type="button" aria-label="关闭大图">✕</button></div><div class="viewer-stage"><img id="viewer-image" alt=""></div><div class="viewer-footer"><div><span id="viewer-title"></span><p id="viewer-status" role="status" aria-live="polite"></p></div><div class="viewer-actions"><button id="viewer-previous" type="button" aria-label="上一张作品">←</button><button id="viewer-next" type="button" aria-label="下一张作品">→</button><button id="viewer-original" type="button">加载原图</button><button id="viewer-zoom" type="button" hidden>100% 查看</button><a id="viewer-link" target="_blank" rel="noopener noreferrer">打开原图 ↗</a></div></div></dialog>`;
const page = (title, description, body, active = '', path = '/') => `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#f7f6f2"><title>${esc(title)} · POWER LIN</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="https://gallery-beta.wiki-power.com${path}"><meta property="og:title" content="${esc(title)} · POWER LIN"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:image" content="https://gallery-beta.wiki-power.com${hero[0].largePreview || hero[0].preview}"><link rel="icon" href="/public/assets/favicon.svg" type="image/svg+xml"><link rel="preconnect" href="https://media.wiki-power.com"><link rel="stylesheet" href="/public/beta.css?v=1"><script src="/public/beta.js?v=1" defer></script></head><body>${nav(active)}<main id="main">${body}</main>${footer}${viewer}</body></html>`;
const heading = (kicker, title, text) => `<div class="page-heading"><span class="eyebrow">${kicker}</span><h1>${title}</h1><p>${text}</p></div>`;
const filters = current => `<nav class="filters" aria-label="作品地点"><a href="/works/" ${!current ? 'aria-current="page"' : ''}>全部<span>${all.length}</span></a>${Object.keys(data.gallery).map(category => `<a href="${categoryPath(category)}" ${current === category ? 'aria-current="page"' : ''}>${esc(place(category))}<span>${data.gallery[category].images.length}</span></a>`).join('')}</nav>`;
const cover = category => find(selection.covers[category] || { category, name: data.gallery[category].images[0].name });
const placeCard = category => `<a class="place-card" href="${categoryPath(category)}"><div class="place-image"><img src="${esc(cover(category).preview)}" alt="${esc(place(category))}摄影作品" width="${cover(category).width}" height="${cover(category).height}" loading="lazy" decoding="async"></div><div class="place-caption"><h3>${esc(place(category))}<span>${esc(english(category))}</span></h3><span>${data.gallery[category].images.length} 件作品 ↗</span></div></a>`;

rmSync('dist', { recursive: true, force: true }); mkdirSync('dist', { recursive: true });
cpSync('public', 'dist/public', { recursive: true }); cpSync('_headers', 'dist/_headers');
const write = (path, html) => { const dir = join('dist', path); mkdirSync(dir, { recursive: true }); writeFileSync(join(dir, 'index.html'), html); };
const homepage = `<section class="intro"><div><span class="eyebrow">SELECTED PHOTOGRAPHY</span><h1>风光<span class="ampersand">与</span>人文<span class="intro-english">PHOTOGRAPHY</span></h1></div><p>在山川与日常之间，<br>看见人与地方的关系。<span>BY POWER LIN</span></p></section><section class="hero-pair" aria-label="封面作品">${hero.map((image, i) => photo(image, i, true, i === 0)).join('')}</section><section class="selected-section"><div class="section-heading"><div><span class="eyebrow">01 / SELECTED WORKS</span><h2>精选作品</h2></div><a class="text-link" href="/works/">浏览全部 ${all.length} 件作品 <span>↗</span></a></div><div class="selected-grid">${selected.map((image, i) => photo(image, i)).join('')}</div></section><section class="places-section"><div class="section-heading"><div><span class="eyebrow">02 / PLACES & JOURNEYS</span><h2>沿途所见</h2></div><a class="text-link" href="/places/">探索全部地点 <span>↗</span></a></div><div class="place-grid">${selection.featuredPlaces.map(placeCard).join('')}</div></section><section class="artist-note"><span class="eyebrow">03 / BEHIND THE LENS</span><h2>风景有尺度，<br>日常有温度。</h2><div><p>用摄影记录远方的风景，<br>也记录街巷中平常的一刻。</p><a class="text-link" href="/about/">关于摄影师 <span>↗</span></a></div></section>`;
write('', page('风光与人文摄影', 'POWER LIN 的个人摄影作品，记录风景、城市与日常。', homepage));
const ordered = [...selected, ...all.filter(image => !selected.some(item => item.original === image.original))];
write('works', page('全部作品', '浏览 POWER LIN 的全部风光与人文摄影作品，可按地点选择并查看原图。', `${heading('THE PHOTOGRAPHIC ARCHIVE', '作品档案', `${all.length} 件作品 · ${Object.keys(data.gallery).length} 个相册`)}${filters()}<div class="archive-grid">${ordered.map((image, i) => photo(image, i)).join('')}</div>`, 'works', '/works/'));
for (const [category, value] of Object.entries(data.gallery)) {
  const images = [...selected.filter(image => image.category === category), ...value.images.filter(image => !selected.some(item => item.original === image.original))];
  write(`works/${category}`, page(place(category), `${place(category)}的摄影记录，共 ${images.length} 件作品。`, `${heading(esc(english(category).toUpperCase()), esc(place(category)), `${images.length} 件作品 · 点击照片查看大图与原图`)}${filters(category)}<div class="archive-grid">${images.map((image, i) => photo(image, i)).join('')}</div>`, 'works', categoryPath(category)));
}
write('places', page('地点', '沿地点浏览 POWER LIN 的摄影旅程。', `${heading('PLACES & JOURNEYS', '沿途所见', '从一个地方，走进一组照片。')}<div class="place-grid all-places">${Object.keys(data.gallery).map(placeCard).join('')}</div>`, 'places', '/places/'));
write('about', page('关于', 'POWER LIN，风光与人文摄影。', `<section class="about-layout"><div>${heading('BEHIND THE LENS', 'POWER LIN', '风光与人文摄影 / PHOTOGRAPHY')}<h2>在山川与日常之间。</h2><p>记录风景、城市，以及人与地方的关系。<br>既看辽阔的远方，也看街巷里平常的一刻。</p><p>这里是我的个人摄影作品档案。<br>你可以从精选作品开始，也可以按地点慢慢浏览。</p><div class="about-links"><a class="text-link" href="/works/">浏览作品 ↗</a><a class="text-link" href="https://wiki-power.com/" target="_blank" rel="noopener noreferrer">个人网站 ↗</a><a class="text-link" href="https://github.com/linyuxuanlin" target="_blank" rel="noopener noreferrer">GitHub ↗</a></div></div>${photo(find(selection.about), 0, true)}</section>`, 'about', '/about/'));
writeFileSync('dist/404.html', page('这一页尚未抵达', '找不到这个页面。', `${heading('404 / OFF THE MAP', '这一页尚未抵达。', '回到作品，继续看见。')}<a class="text-link" href="/works/">返回作品档案 ↗</a>`));
writeFileSync('dist/_redirects', Object.keys(data.gallery).map(category => `/${category} ${categoryPath(category)} 301`).join('\n') + '\n');
writeFileSync('dist/robots.txt', 'User-agent: *\nAllow: /\nSitemap: https://gallery-beta.wiki-power.com/sitemap.xml\n');
const routes = ['/', '/works/', '/places/', '/about/', ...Object.keys(data.gallery).map(categoryPath)];
writeFileSync('dist/sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${routes.map(path => `<url><loc>https://gallery-beta.wiki-power.com${path}</loc></url>`).join('')}</urlset>`);
console.log(`Built ${routes.length} editorial pages, ${all.length} photos, ${selected.length} selected works.`);
