import { readFileSync, writeFileSync, mkdirSync, rmSync, cpSync } from 'node:fs';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { site, siteURL } from './site-config.js';
import { previewMetadata } from './image-metadata.js';
import { seoHead, sitemap, imageObject, escapeHTML } from './seo.js';
import { commissionBody } from './commission.js';

const data = JSON.parse(readFileSync('gallery-index.json', 'utf8'));
const selection = JSON.parse(readFileSync('curation.json', 'utf8'));
const names = { Australia: ['澳大利亚', 'Australia'], Bankok: ['曼谷', 'Bangkok'], Chaozhou: ['潮州', 'Chaozhou'], Hongkong: ['香港', 'Hong Kong'], Jeju: ['济州岛', 'Jeju'], Kyoto: ['京都', 'Kyoto'], Macau: ['澳门', 'Macau'], Nanjing: ['南京', 'Nanjing'], Osaka: ['大阪', 'Osaka'], Other: ['途中', 'Elsewhere'], Shanghai: ['上海', 'Shanghai'], Singapore: ['新加坡', 'Singapore'], Tokyo: ['东京', 'Tokyo'], Vietnam: ['越南', 'Vietnam'], Xiamen: ['厦门', 'Xiamen'], exhibition: ['展览现场', 'Exhibitions'] };
const all = Object.values(data.gallery).flatMap(category => category.images);
const esc = escapeHTML;
const metadata = await previewMetadata(all);
const assetVersion = createHash('sha256').update(readFileSync('public/beta.css')).update(readFileSync('public/beta.js')).digest('hex').slice(0, 12);
const find = pick => {
  const image = all.find(item => item.category === pick.category && item.name === pick.name);
  if (!image) throw new Error(`Missing selection: ${pick.category}/${pick.name}`);
  const caption = [...selection.hero, ...selection.selected].find(item => item.category === pick.category && item.name === pick.name);
  return { ...image, ...caption, ...pick };
};
const selected = selection.selected.map(find), hero = selection.hero.map(find);
const featured = [...new Map([...hero, ...selected].map(image => [image.category + '/' + image.name, image])).values()];
const featuredIds = new Set(featured.map(image => image.category + '/' + image.name));
let language = 'zh';
const t = (zh, en) => language === 'en' ? en : zh;
const local = path => language === 'en' ? '/en' + path : path;
const english = category => names[category]?.[1] || category;
const place = category => t(names[category]?.[0] || category, english(category));
const categoryPath = category => local(`/works/${encodeURIComponent(category)}/`);
const detailPath = image => `/photographs/${encodeURIComponent(image.category)}/${encodeURIComponent(image.name)}/`;
const emailHref = () => `mailto:${site.email}?subject=${encodeURIComponent(t('摄影合作与作品咨询', 'Photography commission and licensing enquiry'))}&body=${encodeURIComponent(t('项目类型：\n拍摄地点：\n日期与时长：\n参考作品链接：\n交付与使用需求：\n预算：\n联系方式：\n', 'Project type:\nLocation:\nDate and duration:\nReference photograph links:\nDeliverables and usage:\nBudget:\nContact details:\n'))}`;
const photo = (image, index = 0, large = false, priority = false, sizes = '(max-width: 700px) calc(100vw - 40px), (max-width: 1560px) 45vw, 650px') => {
  const label = t(image.title, image.titleEn) || `${place(image.category)} · ${image.name}`;
  const full = large && image.largePreview ? image.largePreview : image.preview;
  const preview = metadata.get(image.preview), fullSize = metadata.get(full);
  const hasDetail = featuredIds.has(image.category + '/' + image.name);
  return `<figure class="photo${large ? ' photo-large' : ''}"><a class="photo-open" href="${esc(image.original)}" target="_blank" rel="noopener noreferrer" data-photo data-photo-id="${esc(image.category + '/' + image.name)}" ${hasDetail ? `data-share-url="${esc(siteURL(local(detailPath(image))))}"` : ''} data-preview="${esc(full)}" data-title="${esc(label)}" data-place="${esc(place(image.category))}" aria-label="${t('查看作品：', 'View photograph: ')}${esc(label)}"><img src="${esc(image.preview)}" ${full !== image.preview ? `srcset="${esc(image.preview)} ${preview.width}w, ${esc(full)} ${fullSize.width}w" sizes="${esc(sizes)}"` : ''} width="${preview.width}" height="${preview.height}" alt="${esc(t(image.description, image.descriptionEn) || label)}" loading="${priority ? 'eager' : 'lazy'}" ${priority ? 'fetchpriority="high"' : ''} decoding="async"></a><figcaption>${hasDetail ? `<a class="photo-title" href="${local(detailPath(image))}">${esc(label)}</a>` : `<span>${esc(label)}</span>`}<span class="photo-index">${String(index + 1).padStart(2, '0')} / ${esc(english(image.category))}</span></figcaption></figure>`;
};
const nav = (active, path) => `<a class="skip" href="#main">${t('跳到作品', 'Skip to content')}</a><header class="site-header"><a class="wordmark" href="${local('/')}" aria-label="${t('Power’s Gallery 首页', 'Power’s Gallery home')}">Power’s Gallery<span>PHOTOGRAPHY</span></a><div class="header-controls"><a class="language-switch" href="${language === 'en' ? path : '/en' + path}" data-language="${t('en', 'zh')}" lang="${t('en', 'zh-CN')}" aria-label="${t('Switch to English', '切换为中文')}">${t('EN', '中')}</a><button class="menu-toggle" type="button" aria-label="${t('打开导航', 'Open navigation')}" aria-expanded="false" aria-controls="site-nav"><span></span><span></span></button></div><nav id="site-nav" aria-label="${t('主导航', 'Main navigation')}">${[['works', '/works/', '作品', 'Works'], ['places', '/places/', '地点', 'Places'], ['about', '/about/', '关于', 'About']].map(([key, href, zh, en]) => `<a href="${local(href)}" ${active === key ? 'aria-current="page"' : ''}>${t(zh, en)}<span>${t(en.toUpperCase(), { works: 'PHOTOGRAPHS', places: 'JOURNEYS', about: 'CONTACT' }[key])}</span></a>`).join('')}</nav></header>`;
const footer = () => `<footer class="site-footer"><a class="footer-name" href="${local('/')}">Power’s Gallery</a><p>${t('风光与人文摄影', 'Landscape & people')}<span>LANDSCAPE & HUMAN STORIES</span></p><a class="footer-inquiry" href="${local('/photography/')}">${t('摄影合作', 'Photography enquiries')} ↗</a><a href="https://gallery.wiki-power.com/" target="_blank" rel="noopener noreferrer">${t('原版相册', 'Original gallery')} ↗</a><span class="copyright">© ${new Date().getFullYear()} Power’s Gallery</span></footer>`;
const viewer = () => `<dialog id="viewer" aria-label="${t('作品大图', 'Photograph viewer')}" aria-labelledby="viewer-title"><div class="viewer-top"><span id="viewer-place"></span><button id="viewer-close" type="button" aria-label="${t('关闭大图', 'Close photograph')}">✕</button></div><div class="viewer-stage"><img id="viewer-image" alt=""><span id="viewer-watermark" aria-hidden="true">© Power’s Gallery</span></div><div class="viewer-footer"><div><span id="viewer-title"></span><p id="viewer-status" role="status" aria-live="polite"></p></div><div class="viewer-actions"><button id="viewer-previous" type="button" aria-label="${t('上一张作品', 'Previous photograph')}">←</button><button id="viewer-next" type="button" aria-label="${t('下一张作品', 'Next photograph')}">→</button><button id="viewer-share" type="button">${t('复制链接', 'Copy link')}</button><button id="viewer-original" type="button">${t('加载原图', 'Load original')}</button><button id="viewer-zoom" type="button" hidden>${t('100% 查看', 'View at 100%')}</button><a id="viewer-link" target="_blank" rel="noopener noreferrer">${t('打开原图', 'Open original')} ↗</a></div></div></dialog>`;
const page = (title, description, body, active = '', path = '/', options = {}) => {
  const breadcrumbs = options.breadcrumbs || (path === '/' ? [] : [{ name: site.name, path: '/' }, { name: title, path }]);
  const head = seoHead({ title, description, path, language, metadata, image: options.image || hero[0], breadcrumbs, type: options.type || 'WebPage', mainEntity: options.mainEntity, noindex: options.noindex });
  return `<!doctype html><html lang="${t('zh-CN', 'en')}" data-language="${language}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#f7f6f2">${head}<link rel="icon" href="/public/assets/favicon.svg" type="image/svg+xml"><link rel="preconnect" href="https://media.wiki-power.com"><link rel="stylesheet" href="/public/beta.css?v=${assetVersion}"><script src="/public/beta.js?v=${assetVersion}" defer></script></head><body>${nav(active, path)}<main id="main">${body}</main>${footer()}${viewer()}</body></html>`;
};
const heading = (kicker, title, text) => `<div class="page-heading"><span class="eyebrow">${kicker}</span><h1>${title}</h1><p>${text}</p></div>`;
const filters = current => `<nav class="filters" aria-label="${t('作品地点', 'Photograph locations')}"><a href="${local('/works/')}" ${!current ? 'aria-current="page"' : ''}>${t('全部', 'All')}<span>${all.length}</span></a>${Object.keys(data.gallery).map(category => `<a href="${categoryPath(category)}" ${current === category ? 'aria-current="page"' : ''}>${esc(place(category))}<span>${data.gallery[category].images.length}</span></a>`).join('')}</nav>`;
const cover = category => find(selection.covers[category] || { category, name: data.gallery[category].images[0].name });
const placeCard = category => `<a class="place-card" href="${categoryPath(category)}"><div class="place-image"><img src="${esc(cover(category).preview)}" alt="${esc(place(category))} ${t('摄影作品', 'photographs')}" width="${cover(category).width}" height="${cover(category).height}" loading="lazy" decoding="async"></div><div class="place-caption"><h3>${esc(place(category))}<span>${t(esc(english(category)), 'PHOTOGRAPHIC JOURNEY')}</span></h3><span>${data.gallery[category].images.length} ${t('件作品', 'works')} ↗</span></div></a>`;

rmSync('dist', { recursive: true, force: true }); mkdirSync('dist', { recursive: true });
cpSync('public', 'dist/public', { recursive: true }); cpSync('_headers', 'dist/_headers');
const routes = [], redirects = [];
const write = (path, html, images = []) => {
  const relative = local('/' + path).slice(1), dir = join('dist', relative);
  mkdirSync(dir, { recursive: true }); writeFileSync(join(dir, 'index.html'), html);
  const basePath = '/' + (path ? path + '/' : '');
  routes.push({ path: local(basePath), basePath, images });
};
const ordered = [...selected, ...all.filter(image => !selected.some(item => item.original === image.original))];
for (language of ['zh', 'en']) {
  const homepage = `<section class="intro"><div><span class="eyebrow">SELECTED PHOTOGRAPHY</span><h1>${t('风光<span class="ampersand">与</span>人文', 'Landscape<span class="ampersand">&</span>people')}<span class="intro-english">PHOTOGRAPHY</span></h1></div><p>${t('在山川与日常之间，<br>看见人与地方的关系。', 'Between landscapes and daily life,<br>seeing people in their surroundings.')}<span>LANDSCAPE & HUMAN STORIES</span><a class="intro-inquiry" href="${local('/photography/')}">${t('上海摄影师 · 拍摄合作 ↗', 'Shanghai photographer · Commissions ↗')}</a></p></section><section class="hero-pair" aria-label="${t('封面作品', 'Featured photographs')}">${hero.map((image, i) => photo(image, i, true, i === 0, i === 0 ? '(max-width: 700px) calc(100vw - 40px), (max-width: 1560px) 60vw, 950px' : '(max-width: 700px) calc((100vw - 40px) * .74), (max-width: 1560px) 28vw, 430px')).join('')}</section><section class="selected-section"><div class="section-heading"><div><span class="eyebrow">01 / SELECTED WORKS</span><h2>${t('精选作品', 'Selected works')}</h2></div><a class="text-link" href="${local('/works/')}">${t(`浏览全部 ${all.length} 件作品`, `View all ${all.length} photographs`)} <span>↗</span></a></div><div class="selected-grid">${selected.map((image, i) => photo(image, i)).join('')}</div></section><section class="places-section"><div class="section-heading"><div><span class="eyebrow">02 / PLACES & JOURNEYS</span><h2>${t('沿途所见', 'Places & journeys')}</h2></div><a class="text-link" href="${local('/places/')}">${t('探索全部地点', 'Explore all places')} <span>↗</span></a></div><div class="place-grid">${selection.featuredPlaces.map(placeCard).join('')}</div></section><section class="artist-note"><span class="eyebrow">03 / BEHIND THE LENS</span><h2>${t('风景有尺度，<br>日常有温度。', 'Scale in landscapes.<br>Warmth in daily life.')}</h2><div><p>${t('用摄影记录远方的风景，<br>也记录街巷中平常的一刻。', 'Photographs of distant landscapes,<br>and ordinary moments along the way.')}</p><a class="text-link" href="${local('/about/')}">${t('关于摄影师', 'About the photographer')} <span>↗</span></a></div></section>`;
  write('', page(t('上海摄影师 · 品牌商业、活动纪实与旅行摄影', 'Shanghai Photographer · Brand, Event & Travel Photography'), t('Power 是一位在上海的摄影师，提供旅行人文、活动纪实、风景与品牌商业摄影。浏览精选作品，咨询拍摄合作、作品授权与收藏。', 'Power is a Shanghai-based photographer working in travel, documentary, events, landscapes and brand photography. Explore the portfolio and enquire about a commission or image licence.'), homepage), [...hero, ...selected]);
  write('works', page(t('全部作品', 'All photographs'), t('浏览 Power’s Gallery 的全部风光与人文摄影作品，可按地点选择并查看原图。', 'Explore the full archive by location and view the original photographs.'), `${heading('THE PHOTOGRAPHIC ARCHIVE', t('作品档案', 'The archive'), t(`${all.length} 件作品 · ${Object.keys(data.gallery).length} 个相册`, `${all.length} photographs · ${Object.keys(data.gallery).length} collections`))}${filters()}<div class="archive-grid">${ordered.map((image, i) => photo(image, i)).join('')}</div>`, 'works', '/works/', { type: 'CollectionPage' }), ordered);
  for (const [category, value] of Object.entries(data.gallery)) {
    const images = [...selected.filter(image => image.category === category), ...value.images.filter(image => !selected.some(item => item.original === image.original))];
    write(`works/${category}`, page(t(`${place(category)}摄影作品`, `${place(category)} Photography`), t(`${place(category)}的摄影记录，共 ${images.length} 件作品。`, `${images.length} photographs from ${place(category)}.`), `${heading(esc(english(category).toUpperCase()), esc(place(category)), t(`${images.length} 件作品 · 点击照片查看大图与原图`, `${images.length} photographs · Select a photograph to view its original`))}${filters(category)}<div class="archive-grid">${images.map((image, i) => photo(image, i)).join('')}</div>`, 'works', `/works/${category}/`, { type: 'CollectionPage', image: cover(category) }), images);
    redirects.push(`${local('/' + category)} ${categoryPath(category)} 301`);
  }
  write('places', page(t('地点', 'Places'), t('沿地点浏览 Power’s Gallery 的摄影旅程。', 'Explore the photographic journeys in Power’s Gallery.'), `${heading('PLACES & JOURNEYS', t('沿途所见', 'Places & journeys'), t('从一个地方，走进一组照片。', 'A place, a collection, a different way of seeing.'))}<div class="place-grid all-places">${Object.keys(data.gallery).map(placeCard).join('')}</div>`, 'places', '/places/', { type: 'CollectionPage' }), Object.keys(data.gallery).map(cover));
  const about = `<section class="about-layout"><div>${heading('BEHIND THE LENS', 'Power’s Gallery', t('风光与人文摄影 / PHOTOGRAPHY', 'LANDSCAPE & HUMAN STORIES'))}<h2>${t('在山川与日常之间。', 'Between landscapes and daily life.')}</h2><p>${t('记录风景、城市，以及人与地方的关系。<br>既看辽阔的远方，也看街巷里平常的一刻。', 'Photographs of landscapes, cities and the relationship between people and places.<br>A view of the wider world, and the ordinary moments within it.')}</p><p>${t('我是 Power，一位在上海的摄影师。<br>拍摄旅行人文、活动纪实、风景与品牌商业，也提供作品授权。', 'I’m Power, a photographer based in Shanghai.<br>I work in travel, documentary, events, landscapes and brand photography, and offer image licensing.')}</p><section class="contact-note" aria-labelledby="contact-heading"><span class="eyebrow">COLLABORATIONS & COLLECTIONS</span><h2 id="contact-heading">${t('合作与作品收藏', 'Collaborations & collecting')}</h2><p>${t('拍摄委托、品牌合作、作品授权与购买，欢迎来信。<br>请附上项目类型、地点、日期、使用需求与预算，或感兴趣的作品链接。', 'For commissions, brand projects, licensing or collecting works, please get in touch.<br>Include the project type, location, date, usage and budget, or a link to a photograph.')}</p><a class="contact-email" href="${emailHref()}">${esc(site.email)} <span>↗</span></a></section><section class="copyright-note" aria-labelledby="copyright-heading"><h2 id="copyright-heading">${t('版权声明', 'Copyright')}</h2><p>${t('本站摄影作品版权归 Power 所有。未经许可，请勿复制、转载或用于商业用途。浏览与下载原图不代表取得作品使用授权；如需授权或购买，请通过以上邮箱联系。', 'All photographs on this website are copyright © Power. Please do not reproduce, republish or use them commercially without permission. Viewing or downloading an original does not grant a licence to use it. For licensing or purchases, contact the email above.')}</p></section><div class="about-links"><a class="text-link" href="${local('/photography/')}">${t('拍摄服务与合作流程', 'Photography services & enquiries')} ↗</a><a class="text-link" href="${local('/works/')}">${t('浏览作品', 'Explore the works')} ↗</a><a class="text-link" href="https://wiki-power.com/" target="_blank" rel="noopener noreferrer">${t('个人网站', 'Personal website')} ↗</a><a class="text-link" href="https://github.com/linyuxuanlin" target="_blank" rel="noopener noreferrer">GitHub ↗</a></div></div>${photo(find(selection.about), 0, true, true)}</section>`;
  write('about', page(t('关于上海摄影师 Power · 拍摄合作与作品授权', 'About Power · Shanghai Photographer & Image Licensing'), t('了解上海摄影师 Power 的创作方向：旅行人文、活动纪实、风景与品牌商业摄影。联系拍摄委托、作品授权和收藏。', 'Meet Power, a photographer based in Shanghai. Travel, documentary, event, landscape and brand photography, commissions and image licensing.'), about, 'about', '/about/', { type: 'AboutPage', image: find(selection.about), mainEntity: { '@id': siteURL('/#photographer') } }), [find(selection.about)]);
  const commissionImages = [selected[1], selected[2], selected[5]];
  const commission = commissionBody({ t, local, photo, images: commissionImages, heading, esc, site, emailHref });
  write('photography', page(t('上海摄影师 · 品牌商业、活动纪实与旅行人文拍摄', 'Shanghai Photography Services · Brands, Events & Travel'), t('在上海的摄影师 Power，承接旅行人文、活动纪实、风景和品牌商业摄影。了解拍摄方向与合作流程，发送项目需求并咨询报价、作品授权。', 'Commission Shanghai-based photographer Power for travel, documentary, events, landscapes and brand projects. Share your brief for a quote or enquire about image licensing.'), commission, '', '/photography/', { image: commissionImages[0], mainEntity: { '@type': 'Service', name: t('摄影拍摄与作品授权', 'Photography commissions and image licensing'), provider: { '@id': siteURL('/#photographer') }, areaServed: { '@type': 'City', name: site.city[language] }, serviceType: site.services.map(service => service[language]) } }), commissionImages);
  for (const image of featured) {
    const path = detailPath(image), title = t(image.title, image.titleEn), description = t(image.description, image.descriptionEn);
    const crumbs = [{ name: site.name, path: '/' }, { name: t('作品', 'Photographs'), path: '/works/' }, { name: place(image.category), path: `/works/${image.category}/` }, { name: title, path }];
    const body = `<nav class="breadcrumbs" aria-label="${t('当前位置', 'Breadcrumbs')}">${crumbs.slice(0, -1).map(crumb => `<a href="${local(crumb.path)}">${esc(crumb.name)}</a>`).join('<span aria-hidden="true">/</span>')}</nav>${heading(esc(english(image.category).toUpperCase()), esc(title), esc(description))}<section class="photograph-detail">${photo(image, 0, true, true, '(max-width: 700px) calc(100vw - 40px), (max-width: 1560px) 82vw, 1200px')}<div class="photograph-context"><p>${t(`摄影：${site.photographer} · 地点：${place(image.category)}。作品版权归摄影师所有。`, `Photograph by ${site.photographer} · ${place(image.category)}. Copyright remains with the photographer.`)}</p><p>${t('如需授权、收藏，或希望合作拍摄，请附上本页链接与用途来信。', 'For licensing, collecting or a photographic commission, include this page link and your intended use in an enquiry.')}</p><a class="text-link" href="${local('/photography/#licensing')}">${t('咨询作品授权与摄影合作', 'Enquire about licensing & commissions')} ↗</a><a class="text-link" href="${categoryPath(image.category)}">${t('更多' + place(image.category) + '作品', 'More photographs from ' + place(image.category))} ↗</a></div></section>`;
    write(path.slice(1, -1), page(t(`${title} · ${place(image.category)}摄影`, `${title} · ${place(image.category)} Photography`), `${description} ${t('Power 的摄影作品，可咨询授权与拍摄合作。', 'A photograph by Power. Enquire about image licensing or a commission.')}`, body, 'works', path, { image, breadcrumbs: crumbs, mainEntity: imageObject(image, language, metadata) }), [image]);
  }
  const missing = page(t('这一页尚未抵达', 'Off the map'), t('找不到这个页面。', 'This page could not be found.'), `${heading('404 / OFF THE MAP', t('这一页尚未抵达。', 'This page is off the map.'), t('回到作品，继续看见。', 'Return to the archive and keep exploring.'))}<a class="text-link" href="${local('/works/')}">${t('返回作品档案', 'Return to the archive')} ↗</a>`, '', '/404.html', { noindex: true });
  writeFileSync(join('dist', language === 'en' ? 'en/404.html' : '404.html'), missing);
}
for (const host of site.canonicalRedirectHosts) {
  if (!/^[a-z0-9.-]+$/.test(host) || host === new URL(site.url).hostname) throw new Error('Invalid canonical redirect host');
  redirects.unshift(`https://${host}/* ${site.url}/:splat 301`);
}
writeFileSync('dist/_redirects', redirects.join('\n') + '\n');
writeFileSync('dist/robots.txt', `User-agent: *\nAllow: /\nSitemap: ${siteURL('/sitemap.xml')}\n`);
writeFileSync('dist/sitemap.xml', sitemap(routes));
// Prebuilt root supports the existing Pages project's static branch previews.
for (const route of routes) {
  const relative = route.path.slice(1); mkdirSync(relative || '.', { recursive: true });
  cpSync(join('dist', relative, 'index.html'), join(relative, 'index.html'));
}
for (const file of ['404.html', 'en/404.html', '_redirects', 'robots.txt', 'sitemap.xml']) cpSync(join('dist', file), file);
console.log(`Built ${routes.length} bilingual pages, ${all.length} photos, ${selected.length} selected works.`);
