export function commissionBody({ t, local, photo, images, heading, esc, site, emailHref }) {
  const descriptions = [
    t('记录旅途中的人物、街巷与地方生活。适合旅行专题、目的地故事与人文内容。', 'People, streets and everyday life along the way. For travel stories, destination features and documentary projects.'),
    t('关注活动中的人物、氛围和关键时刻。沟通活动流程、使用场景与需要记录的内容。', 'People, atmosphere and key moments at an event. Share the schedule, intended use and moments that matter.'),
    t('以自然风景、城市空间与环境细节呈现地方的独特气质。可咨询拍摄或现有作品授权。', 'Natural landscapes, urban spaces and environmental details. Enquire about a commission or licensing an existing photograph.'),
    t('围绕品牌的视觉需求沟通拍摄方向、参考风格和传播用途，确认适合项目的拍摄方案。', 'Photography shaped around a brand’s visual brief. Discuss direction, references and usage to define the right approach.')
  ];
  return `${heading('PHOTOGRAPHY & COMMISSIONS', t('上海摄影师 · 摄影合作', 'Shanghai photographer · Commissions'), t('旅行人文 · 活动纪实 · 风景 · 品牌商业', 'Travel & documentary · Events · Landscapes · Brand & commercial'))}
<section class="commission-lead"><div><h2>${t('让照片，讲述你的故事。', 'Photographs that tell your story.')}</h2><p>${t('我是 Power，一位在上海的摄影师。我的作品关注风景、日常，以及人与地方的关系。欢迎交流拍摄委托、品牌内容与作品授权。', 'I’m Power, a photographer based in Shanghai. My work explores landscapes, everyday life and the relationship between people and places. Get in touch about a commission, brand project or image licence.')}</p><a class="contact-email" href="${emailHref()}">${t('沟通拍摄需求', 'Discuss your project')} <span>↗</span></a></div><p class="commission-aside">${t('先看作品，再聊需求。<br>每个项目的拍摄范围、交付内容与使用授权，都在合作前沟通确认。', 'Explore the work, then share your brief.<br>Scope, deliverables and usage rights are agreed before a project begins.')}</p></section>
<section aria-labelledby="services-heading" class="commission-section"><div class="section-heading"><div><span class="eyebrow">01 / WHAT WE CAN CREATE</span><h2 id="services-heading">${t('拍摄方向', 'Photography services')}</h2></div></div><div class="service-grid">${site.services.map((service, index) => `<article><span class="eyebrow">0${index + 1}</span><h3>${esc(service[t('zh', 'en')])}</h3><p>${descriptions[index]}</p></article>`).join('')}</div></section>
<section class="commission-section" aria-labelledby="commission-works-heading"><div class="section-heading"><div><span class="eyebrow">02 / A WAY OF SEEING</span><h2 id="commission-works-heading">${t('从作品开始', 'Start with the work')}</h2></div><a class="text-link" href="${local('/works/')}">${t('浏览完整作品档案', 'Explore the full archive')} ↗</a></div><div class="commission-works">${images.map((image, index) => photo(image, index)).join('')}</div><p class="section-note">${t('这些个人摄影作品展示我的观察与表达方式。欢迎带着你的参考与需求来沟通。', 'These personal photographs show my approach to seeing and storytelling. Share your own references and project goals.')}</p></section>
<section class="commission-section inquiry-section" id="inquiry" aria-labelledby="inquiry-heading"><div><span class="eyebrow">03 / YOUR BRIEF</span><h2 id="inquiry-heading">${t('把想法，变成拍摄计划。', 'From an idea to a photographic brief.')}</h2><p>${t('来信时附上以下信息，有助于我们明确项目范围与报价。暂时没有完整方案也没关系，可以从你的想法开始。', 'These details help us define the scope and quote. Your brief need not be complete — an initial idea is a good place to start.')}</p></div><div><ul class="inquiry-list"><li>${t('项目类型、品牌或活动介绍', 'Project type, brand or event overview')}</li><li>${t('拍摄地点、日期与预计时长', 'Location, date and estimated duration')}</li><li>${t('参考作品、视觉风格与需要记录的内容', 'Visual references and what you want photographed')}</li><li>${t('交付需求、使用渠道、授权范围与预算', 'Deliverables, usage channels, licensing scope and budget')}</li></ul><a class="contact-email" href="${emailHref()}">${esc(site.email)} <span>↗</span></a></div></section>
<section class="commission-section licensing-section" id="licensing" aria-labelledby="licensing-heading"><span class="eyebrow">04 / IMAGE LICENSING</span><h2 id="licensing-heading">${t('作品授权与收藏', 'Image licensing & collecting')}</h2><p>${t('如果你希望使用本站的某张照片，请在来信中附上作品页面链接，并说明用途、使用渠道、地区与期限。授权范围与费用将根据具体需求确认；下载原图不代表获得使用授权。', 'To license a photograph, include its page link and describe the intended use, channels, territory and duration. Scope and fees depend on the brief; downloading an original does not grant usage rights.')}</p><a class="text-link" href="${local('/about/#copyright-heading')}">${t('阅读版权说明', 'Read the copyright notice')} ↗</a></section>`;
}
