import { readFileSync } from 'node:fs';

export const exhibition = JSON.parse(readFileSync(new URL('../exhibition.json', import.meta.url), 'utf8'));

// Chapters are a sequence of the existing selection, not a second image archive.
export function exhibitionBody({ t, local, esc, photo, hero, selected, allCount, placeCards }) {
  const works = new Map(selected.map(image => [image.category + '/' + image.name, image]));
  const sequence = exhibition.chapters.flatMap(chapter => chapter.works);
  if (sequence.length !== works.size || new Set(sequence).size !== sequence.length || sequence.some(id => !works.has(id))) {
    throw new Error('Exhibition chapters must include each selected photograph exactly once.');
  }
  const paragraphs = (zh, en) => t(zh, en).map(text => `<p>${esc(text)}</p>`).join('');
  let position = hero.length;
  return `<section class="intro exhibition-intro"><div><span class="eyebrow">POWER / SELECTED PHOTOGRAPHS</span><h1>${esc(t(exhibition.title, exhibition.titleEn))}</h1><span class="exhibition-subtitle" ${t('lang="en"', '')}>${t('A BRIEF PRESENCE', 'PHOTOGRAPHS BY POWER')}</span></div><div class="exhibition-standfirst"><p>${esc(t(exhibition.standfirst, exhibition.standfirstEn))}</p><span class="eyebrow">14 ${t('幅作品', 'PHOTOGRAPHS')} / POWER</span></div></section><section class="hero-pair" aria-label="${t('序章作品', 'Opening photographs')}">${hero.map((image, i) => photo(image, i, true, i === 0, i === 0 ? '(max-width: 700px) calc(100vw - 40px), (max-width: 1560px) 60vw, 950px' : '(max-width: 700px) calc((100vw - 40px) * .74), (max-width: 1560px) 28vw, 430px')).join('')}</section><section class="exhibition-prologue" aria-labelledby="selection-heading"><div><span class="eyebrow">ON THIS SELECTION</span><h2 id="selection-heading">${t('关于这次选片', 'On this selection')}</h2></div><div>${paragraphs(exhibition.introduction, exhibition.introductionEn)}</div></section>${exhibition.chapters.map((chapter, i) => `<section class="exhibition-chapter" aria-labelledby="${chapter.id}-heading"><div class="chapter-heading"><div><span class="eyebrow">${String(i + 1).padStart(2, '0')} / ${esc(chapter.titleEn.toUpperCase())}</span><h2 id="${chapter.id}-heading">${esc(t(chapter.title, chapter.titleEn))}</h2></div><p>${esc(t(chapter.text, chapter.textEn))}</p></div><div class="selected-grid">${chapter.works.map(id => photo(works.get(id), position++)).join('')}</div></section>`).join('')}<div class="exhibition-archive-link"><span class="eyebrow">THE PHOTOGRAPHIC ARCHIVE</span><a class="text-link" href="${local('/works/')}">${t(`浏览全部 ${allCount} 幅作品`, `Explore all ${allCount} photographs`)} <span>↗</span></a></div><section class="places-section"><div class="section-heading"><div><span class="eyebrow">PLACES / INDEX</span><h2>${t('影像发生的地方', 'Places in the photographs')}</h2></div><a class="text-link" href="${local('/places/')}">${t('地点索引', 'Place index')} <span>↗</span></a></div><div class="place-grid">${placeCards}</div></section><section class="artist-note"><span class="eyebrow">A NOTE ON LOOKING</span><h2>${t('在经过的地方，<br>停留片刻。', 'A pause<br>along the way.')}</h2><div><p>${t('从海岸到街巷，照片留住了短暂的相遇，也留下了继续观看的距离。', 'From coast to street, photographs hold a brief encounter and leave room to keep looking.')}</p><a class="text-link" href="${local('/about/')}">${t('创作自述', 'Artist statement')} <span>↗</span></a></div></section>`;
}
