import { exhibitionPath, exhibitionPhotoIds } from './exhibitions.js';

export function exhibitionIndexBody({ exhibitions, findId, metadata, t, local, esc, allCount }) {
  const cards = exhibitions.map((exhibition, index) => {
    const cover = findId(exhibition.cover), source = cover.largePreview || cover.preview, dimensions = metadata.get(source);
    return `<a class="exhibition-card" data-exhibition="${esc(exhibition.slug)}" href="${local(exhibitionPath(exhibition))}"><div class="exhibition-card-image"><img src="${esc(source)}" alt="${esc(t(cover.description, cover.descriptionEn) || t(exhibition.title, exhibition.titleEn))}" width="${dimensions.width}" height="${dimensions.height}" loading="${index === 0 ? 'eager' : 'lazy'}" ${index === 0 ? 'fetchpriority="high"' : ''} decoding="async"></div><div class="exhibition-card-copy"><span class="eyebrow">${String(index + 1).padStart(2, '0')} / ${exhibition.status === 'archived' ? 'EXHIBITION ARCHIVE' : 'SELECTED PHOTOGRAPHS'}</span><h2>${esc(t(exhibition.title, exhibition.titleEn))}</h2>${t(`<span class="exhibition-card-subtitle" lang="en">${esc(exhibition.titleEn)}</span>`, '')}<p>${esc(t(exhibition.standfirst, exhibition.standfirstEn))}</p><span class="exhibition-card-count">${exhibitionPhotoIds(exhibition).length} ${t('幅作品', 'photographs')} / POWER</span><span class="text-link">${t('进入展览', 'Enter the exhibition')} <span>↗</span></span></div></a>`;
  }).join('');
  return `<section class="exhibition-index-intro"><div><span class="eyebrow">POWER / EXHIBITION INDEX</span><h1>${t('观看的几种方式', 'Ways of looking')}</h1></div><p>${t('照片重新相邻，<br>目光从这里出发。', 'Photographs brought together.<br>Another place to begin.')}</p></section><section class="exhibition-list" aria-label="${t('展览目录', 'Exhibition index')}">${cards || `<p class="exhibition-empty">${t('展览正在编排中。', 'An exhibition is taking shape.')}</p>`}</section><section class="index-archive-note"><div><span class="eyebrow">THE PHOTOGRAPHIC ARCHIVE</span><h2>${t('选辑之外', 'Beyond the selection')}</h2></div><div><p>${t('作品档案保留沿途的影像，也为每一次新的选片提供起点。', 'The archive keeps photographs from along the way, and offers a starting point for each new selection.')}</p><a class="text-link" href="${local('/works/')}">${t(`浏览全部 ${allCount} 幅作品`, `Explore all ${allCount} photographs`)} ↗</a></div></section>`;
}

export function exhibitionBody({ exhibition, t, local, esc, photo, findId, allCount, related }) {
  const opening = exhibition.opening.map(findId), count = exhibitionPhotoIds(exhibition).length;
  const paragraphs = (zh, en) => t(zh, en).map(text => `<p>${esc(text)}</p>`).join('');
  let position = opening.length;
  return `<div class="exhibition-topline"><a class="text-link" href="${local('/')}">← ${t('展览目录', 'Exhibition index')}</a><span class="eyebrow">PHOTOGRAPHS BY POWER</span></div><section class="intro exhibition-intro"><div><span class="eyebrow">POWER / SELECTED PHOTOGRAPHS</span><h1>${esc(t(exhibition.title, exhibition.titleEn))}</h1><span class="exhibition-subtitle" ${t('lang="en"', '')}>${t(esc(exhibition.titleEn.toUpperCase()), 'PHOTOGRAPHS BY POWER')}</span></div><div class="exhibition-standfirst"><p>${esc(t(exhibition.standfirst, exhibition.standfirstEn))}</p><span class="eyebrow">${count} ${t('幅作品', 'PHOTOGRAPHS')} / POWER</span></div></section>${opening.length ? `<section class="hero-pair" aria-label="${t('序章作品', 'Opening photographs')}">${opening.map((image, index) => photo(image, index, true, index === 0, index === 0 ? '(max-width: 700px) calc(100vw - 40px), (max-width: 1560px) 60vw, 950px' : '(max-width: 700px) calc((100vw - 40px) * .74), (max-width: 1560px) 28vw, 430px')).join('')}</section>` : ''}<section class="exhibition-prologue" aria-labelledby="selection-heading"><div><span class="eyebrow">ON THIS SELECTION</span><h2 id="selection-heading">${t('关于这次选片', 'On this selection')}</h2></div><div>${paragraphs(exhibition.introduction, exhibition.introductionEn)}</div></section>${exhibition.chapters.map((chapter, index) => `<section class="exhibition-chapter" aria-labelledby="${chapter.id}-heading"><div class="chapter-heading"><div><span class="eyebrow">${String(index + 1).padStart(2, '0')} / ${esc(chapter.titleEn.toUpperCase())}</span><h2 id="${chapter.id}-heading">${esc(t(chapter.title, chapter.titleEn))}</h2></div><p>${esc(t(chapter.text, chapter.textEn))}</p></div><div class="selected-grid">${chapter.works.map(id => photo(findId(id), position++)).join('')}</div></section>`).join('')}<nav class="exhibition-ending" aria-label="${t('继续观看', 'Continue looking')}"><a class="text-link" href="${local('/')}">← ${t('返回展览目录', 'Return to the exhibition index')}</a>${related ? `<a class="text-link" href="${local(exhibitionPath(related))}">${t('另一场展览：', 'Another exhibition: ')}${esc(t(related.title, related.titleEn))} ↗</a>` : ''}<a class="text-link" href="${local('/works/')}">${t(`全部 ${allCount} 幅作品`, `All ${allCount} photographs`)} ↗</a></nav>`;
}
